// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNqh0kQExWd5X5A7uLNIg0125PX5huN8',
    appId: '1:871455579333:web:b93887d83f5d98fa8f24ac',
    messagingSenderId: '871455579333',
    projectId: 'payment-59ec6',
    authDomain: 'payment-59ec6.firebaseapp.com',
    databaseURL: 'https://payment-59ec6-default-rtdb.firebaseio.com',
    storageBucket: 'payment-59ec6.firebasestorage.app',
    measurementId: 'G-JB4WJ7CFGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmnAEfnhuQsSMYb_tWm7lucruH0wKFYY',
    appId: '1:871455579333:android:5998c105b72fecee8f24ac',
    messagingSenderId: '871455579333',
    projectId: 'payment-59ec6',
    databaseURL: 'https://payment-59ec6-default-rtdb.firebaseio.com',
    storageBucket: 'payment-59ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtz6z101F5kWclgJbdM-ZQEhuqNyKjTUc',
    appId: '1:871455579333:ios:de1b45793e9bde368f24ac',
    messagingSenderId: '871455579333',
    projectId: 'payment-59ec6',
    databaseURL: 'https://payment-59ec6-default-rtdb.firebaseio.com',
    storageBucket: 'payment-59ec6.firebasestorage.app',
    iosClientId: '871455579333-1hb49je34mo59fal55omcvd9iqflucdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtz6z101F5kWclgJbdM-ZQEhuqNyKjTUc',
    appId: '1:871455579333:ios:de1b45793e9bde368f24ac',
    messagingSenderId: '871455579333',
    projectId: 'payment-59ec6',
    databaseURL: 'https://payment-59ec6-default-rtdb.firebaseio.com',
    storageBucket: 'payment-59ec6.firebasestorage.app',
    iosClientId: '871455579333-1hb49je34mo59fal55omcvd9iqflucdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0_Zn3Q9o6kJ0qQwVRFo6VtHj3ClxF9NI',
    appId: '1:871455579333:web:749a0c0dc2ad61b68f24ac',
    messagingSenderId: '871455579333',
    projectId: 'payment-59ec6',
    authDomain: 'payment-59ec6.firebaseapp.com',
    databaseURL: 'https://payment-59ec6-default-rtdb.firebaseio.com',
    storageBucket: 'payment-59ec6.firebasestorage.app',
    measurementId: 'G-VHDBL0L932',
  );
}
